apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  namespace: chat-app
type: Opaque
data:
  DB_USER: "${DB_USER_B64}"
  DB_PASS: "${DB_PASS_B64}"
  MONGO_USER: "${MONGO_USER_B64}"
  MONGO_PASSWORD: "${MONGO_PASSWORD_B64}"
  JWT_SECRET: "${JWT_SECRET_B64}"
